### ISSUE TITLE
Add .moveTransient method

### ISSUE THREAD

**Issue by mattsgarlata** [SpiderStrategies/kalpa-tree#330]

**Comment by mattsgarlata** [comment]
It looks like I didn't look at this closely enough when I gave this a +1.  The general move method works like this:

```
/*
 * Moves a node within the tree
 * If to is missing and the tree is a forest, the node will be moved
 * to a new root node of the forest tree
 */
Tree.prototype.move = function (node, to) {
  // etc
}
```

The first argument is the node that is to be moved.  In the case of the transient, we already know the node so I think the first argument should be omitted.  So I think the moveTransient method should look like this:

```
Tree.prototype.moveTransient = function (to) {
  return Tree.prototype.move.call(this, this.getTransient(), to)
}
```

**Comment by nathanbowser** [comment]
Yea, I wasn't thinking clearly. I'll change it.
