### ISSUE TITLE
Scrollbars cover the right side of the tree nodes in IE11 and Edge

### ISSUE THREAD

**Issue by scottoreilly** [SpiderStrategies/kalpa-tree#349]
This corresponds to https://github.com/SpiderStrategies/Scoreboard/issues/7995.

For debugging purposes I've opened the `ie-scrollbars-covering` branch that adds the pink "A" on the right. When the tree is collapsed, everything is great.

![screen shot 2016-11-09 at 10 53 30 am](https://cloud.githubusercontent.com/assets/1259395/20144575/105b4d70-a66b-11e6-958a-371feb8ca1f3.png)

When you expand the tree and IE adds a scrollbar, it covers the pink As.

![screen shot 2016-11-09 at 10 53 41 am](https://cloud.githubusercontent.com/assets/1259395/20144576/106422d8-a66b-11e6-8a28-581633deb9e9.png)

After a LOT of testing, I've determined that this is caused by the absolute positioning of the `li` elements. When you override the CSS with the following, everything renters perfectly.
```
li.node {
  transform: none !important;
  position: relative !important;
}
```

![screen shot 2016-11-09 at 10 53 30 am](https://cloud.githubusercontent.com/assets/1259395/20144575/105b4d70-a66b-11e6-958a-371feb8ca1f3.png)

![screen shot 2016-11-09 at 11 23 35 am](https://cloud.githubusercontent.com/assets/1259395/20145666/fb37eb0c-a66e-11e6-962f-72f89a8f3d9e.png)

Of course, changing the list nodes to be laid out vertically by the browser will break all of our huge tree performance stuff that only renders visible nodes.

If anyone wants to try to fix this in CSS, I have my examples checked into the `ie-scrollbars-covering` branch. Other than that, the only other option I can think of is to use JS for IE and check for the existence of scrolling content. When it exists, we give the tree `overflow-y: scroll;`. When there's no scrollable content for IE, it can default to the normal styling.

**Comment by scottoreilly** [comment]
If we did this in JS it would be fairly simple. This example is adding margin rather than manually forcing scrollbars. Either would work.

http://stackoverflow.com/questions/18548465/prevent-scroll-bar-from-adding-up-to-the-width-of-page-on-chrome

**Comment by mattsgarlata** [comment]
I have no problem with a JS solution.  I don't think it makes sense to kill ourselves trying to get CSS to work the way we want in IE when a simple JS solution will do the trick.

**Comment by scottoreilly** [comment]
I like to think I'm pretty good at CSS hacks, and I couldn't get this one working. The problem is that as soon as you take an object out of auto-layout with a float or absolute positioning, IE completely ignores any parent scrollbars when setting 100% width.

If we do this with JS, I'd like to try setting `overflow-y: scroll` first. That way we don't hard-code a margin corresponding to a scrollbar width that could change in future browser versions.
