### ISSUE TITLE
Make individual nodes read-only (not moveable)

### ISSUE THREAD

**Issue by jerryorr** [SpiderStrategies/kalpa-tree#369]
Certain nodes in the tree may be immobile (like scorecard template copies), but there could be other nodes in the same tree that _are_ moveable (like "standalone" nodes in a template copy). I can think of two ways to handle it:

 * Add a `moveable` option to the tree, similar to the existing `droppable` option. It's a callback function that gets the node that's being moved and it's current destination, and you return true/false to indicate if it's valid.
 * Add a `moveable` boolean attribute to the tree nodes. In the cases I can think of, this can be determined at render time and doesn't change (a node is either moveable or it isn't).

**Comment by mattsgarlata** [comment]
I vote for the callback.  I don't think it really adds much in terms of complexity, but it's much more powerful.  It's also nice symmetry that it matches how the `droppable` option works.

**Comment by nathanbowser** [comment]
yea, absolutely
