### ISSUE TITLE
Add support for nodes with different heights

### ISSUE THREAD

**Issue by scottoreilly** [SpiderStrategies/kalpa-tree#382]
This isn't due until like August, so no rush. Also, if this is going to be hard, let's not worry about it.

The general idea is the first-level nodes will be tall, and second-level and lower nodes will be shorter. I talked to @nathanbowser about this and he recommended making the height function flexible as a callback.

<img width="505" alt="screen shot 2017-04-28 at 11 15 04 am" src="https://cloud.githubusercontent.com/assets/1259395/25595022/3afdd008-2e91-11e7-8554-0b513d349e1e.png">

**Comment by nathanbowser** [comment]
I started throwing around a few ideas for this, and asked Scott a few questions. Here's some notes he sent me:

> The trees will not be large

>Yes, the cube trees will be arranged with drag and drop

> The requirements of where you can drag are different, though. The first-level things can only be cubes and cubes can only be first-level things. So, if you’re reordering a cube, it’s more an up and down thing.

> Under the cubes are two types of objects, folders and views. They can be arranged in any order within a cube, but they can’t be dragged outside of a cube to a different cube

**Comment by nathanbowser** [comment]
@scottoreilly and @mattsgarlata  Is this needed for SB3 3.2?

**Comment by mattsgarlata** [comment]
This is just cosmetic, so I don't think we need it by any certain date.

**Comment by nathanbowser** [comment]
Talked to @scottoreilly. He's encouraging the designers to pick a single height. This would require a fairly significant rewrite and make things tricky, especially with dnd.

Closing now, but we can reopen if designers are sticklers for the variable height tree.
