### ISSUE TITLE
Add more info to dndstart event

### ISSUE THREAD

**Issue by mattsgarlata** [SpiderStrategies/kalpa-tree#398]
From what I can tell, when DND is happening in the tree, a .stopPropagation is called somewhere along the line, so the only way to tie functionality to DND is to use the built-in `dndstart` event.  That event doesn't have any information about the node being dragged, though.  I think it would be good to include the item being moved as the first argument to the event handler.  I suppose for the sake of symmetry it would be a good idea to also pass that along with the `dndstop` event.

This is to support this issue: https://github.com/SpiderStrategies/Scoreboard/issues/9199

**Comment by nathanbowser** [comment]
Hey @mattsgarlata, reading through #9199 makes me think you should have access to the traveling node, which is the node the user actually moves, too. But we trigger dndstart before the traveler is created. Looks like we moved the dndstart event at one point (https://github.com/SpiderStrategies/kalpa-tree/commit/29143d91f7083449dc412da2e041b68f215746b6). I'm wondering:

1. Do you actually need the traveler node? 

2. If Yes, think we can get away with firing dndstart after the traveler is created? Maybe we can do after it's created, but before it's appended? What do you think?

**Comment by mattsgarlata** [comment]
Yeah I probably do want the traveler.  Maybe it would be best to instead pass an object to the event handler, like `{ node: node, traveler: traveler }`.  

I only see one place in the codebase where we reference any of the dnd events currently, so SB3 should be happy with the event firing after the traveler is created.  I don't know if the kalpa-tree's internals will be cool with that, though.

I would think you would want to have the event fire after the traveler is created and appended.  That way I could attach a tooltip to it.  Would there be some benefit of firing the event before the traveler is appended?  I can only think of a drawback.

**Comment by nathanbowser** [comment]
Nope, I agree with you. Just wasn't sure why we moved it for https://github.com/SpiderStrategies/kalpa-tree/commit/29143d91f7083449dc412da2e041b68f215746b6. But I have a PR coming with the tests still passing, so we should be okay, I hope.

**Comment by mattsgarlata** [comment]
This API isn't quite what I was expecting.  The first node you passed in was called "node" so I thought it was one of the nodes in the tree like with id and label properties, but it's actually the DOM node of the node being moved.  I'm not sure why a caller would be interested in that over the data for the node being moved.  In my case I have no interest in the DOM node being moved, only in the traveler and the data for the node being moved.

I can get that data from the tree, but I think maybe we have an opportunity to come up with a better API here.  You could add the node data as a 4th argument, but I think since there are 4 pieces of salient information here it would be better to pass an object like this

```
this.trigger('dndstart, {
    traveler: this.traveler.node(),
    data: this.get(), // something like { id: 123, label: 'node' }
    el: el, // what is currently referred to as "node"
    layout: d
}
```

**Comment by nathanbowser** [comment]
Honestly this issue is driving me nuts, just tell me exactly what you want.

**Comment by mattsgarlata** [comment]
My previous post has a suggestion for the syntax that I think would work well.
