### ISSUE TITLE
Tree can trigger move events after invalid drop

### ISSUE THREAD

**Issue by mattsgarlata** [SpiderStrategies/kalpa-tree#406]
If I try to drag and drop a node that isn't ever allowed to be dragged, the tree sometimes still triggers move events anyway.

![screen shot 2017-10-06 at 8 38 16 am](https://user-images.githubusercontent.com/1598200/31278126-d1fd3b04-aa71-11e7-9b55-50184036fd95.png)

**Comment by mattsgarlata** [comment]
I'm double checking something real quick to make sure this isn't on my end

**Comment by mattsgarlata** [comment]
I'm pretty sure this is legit.  The `droppable` function isn't even being called by the tree

**Comment by nathanbowser** [comment]
Is this something you see w/ trees outside of the cubes tree in the screenshot?

**Comment by nathanbowser** [comment]
Never mind, found a way to reproduce and a bug.

**Comment by mattsgarlata** [comment]
This is still happening for me, but it was difficult to reproduce at first.  Now I can duplicate it easily.  It looks like the droppable function isn't being called at all in this situation.  I'm on the latest version so I think the prior code changes for this issue are in place.

https://files.slack.com/files-pri/T0293R8M7-F7U2AU0CR/download/droppable_not_being_called.mov

**Comment by nathanbowser** [comment]
@mattsgarlata I don't think this is a bug w/ the latest tree code. In SB3 `cubes-paste-allowed`, if you `return false` right away, this doesn't blow up. Do you just need an extra check in that callback to prevent Private/Shared cubes from moving?

**Comment by nathanbowser** [comment]
@mattsgarlata Hold the phone, I think I found the bug!

**Comment by nathanbowser** [comment]
Never mind, can't find it. PR coming in SB3 though.
