### ISSUE TITLE
Traveling node DOM/style changes

### ISSUE THREAD

**Issue by nathanbowser** [SpiderStrategies/kalpa-tree#416]
@donald-john Would you mind filling in the details of what you need me to do?

**Comment by donald-john** [comment]
Sure, I just need a way to know that the traveling node was the selected node. We can use the same class we're using for the regular selected node.

Example:
![2018-02-07 11 02 18](https://user-images.githubusercontent.com/7981518/35926609-8cc32850-0bf6-11e8-860f-29efba44f874.gif)
