### ISSUE TITLE
Safari label-mask disappears while opening/collapsing nodes

### ISSUE THREAD

**Issue by donald-john** [SpiderStrategies/kalpa-tree#419]
I first noticed this in the `scoreboard-gantt` project but it also appears to be happening in the SB3 trees as well.

**Ignore the choppiness, its from the gif**
*Notice how the label masks take an extra split second to appear and cover the long names?*
![2018-03-20 16 12 49](https://user-images.githubusercontent.com/7981518/37680213-9b56db7c-2c59-11e8-8973-69f1040c7919.gif)
![2018-03-20 16 10 30](https://user-images.githubusercontent.com/7981518/37680150-6ddd590a-2c59-11e8-9ad8-388310f322c3.gif)

**Comment by nathanbowser** [comment]
Dup of https://github.com/SpiderStrategies/Scoreboard/issues/17017

**Comment by nathanbowser** [comment]
See https://github.com/SpiderStrategies/scoreboard-gantt/pull/81 or https://github.com/SpiderStrategies/Scoreboard/issues/17017#issuecomment-381224779 if someone has to hunt down a similar problem at some point. It's related to safari's z-index stack when forcing hardware accelerations with `translate3d`.
