### ISSUE TITLE
Stream classname bug

### ISSUE THREAD

**Issue by nathanbowser** [SpiderStrategies/kalpa-tree#426]
Tom reports:
> in the tree, if i stream some nodes, it looks like if i don’t include nodes that change, those nodes lose their class styling
> so initially i have
> A 
>  - B
>  - C

>all are styled, then i get a stream that sends some info on node C, say the icon changes
nodes A and B lose their classnames when c gets updated

**Comment by vtarchon** [comment]
nm this was caused by a bug in the calling code.
