### ISSUE TITLE
Make node-contents width flush against right side.

### ISSUE THREAD

**Issue by derekstory** [SpiderStrategies/kalpa-tree#479]
@nathanbowser Assigning to you since you handle most of the tree code, but if you want me to update it let me know. Also let me know if you can see any potential issues with my solution.

 In V6, we have a new design for the selected nodes:

<img width="1083" alt="Screenshot 2024-01-12 at 12 17 02 PM" src="https://github.com/SpiderStrategies/kalpa-tree/assets/3791116/59ef0fed-cf3a-4010-a79b-a94c03f9c643">

To achieve this, I think I need to use the `.node-contents` element. However, translates cause nested nodes to get pushed offscreen if its too long:

<img width="467" alt="Screenshot 2024-01-12 at 12 27 34 PM" src="https://github.com/SpiderStrategies/kalpa-tree/assets/3791116/26001703-c5cd-4ef4-947b-ba1424290ab0">

And if its a short label, the node content is too small:
<img width="453" alt="Screenshot 2024-01-12 at 12 27 00 PM" src="https://github.com/SpiderStrategies/kalpa-tree/assets/3791116/862ac554-c6d6-4ba7-bcc7-53d5d6b9f937">

I think we can easily make it flush against the right side by adding `width: calc(100% - ${theXTranslateValue});`. 

Example:
<img width="353" alt="Screenshot 2024-01-12 at 12 15 11 PM" src="https://github.com/SpiderStrategies/kalpa-tree/assets/3791116/3a5731a5-fbd6-467c-8fdb-fdfb52f03e1c">

Which would make the short and long examples flush against the side and give me something to work with:

<img width="458" alt="Screenshot 2024-01-12 at 12 28 41 PM" src="https://github.com/SpiderStrategies/kalpa-tree/assets/3791116/eab7cb88-8a13-4424-ae2b-c8e7b2165c36">
<img width="445" alt="Screenshot 2024-01-12 at 12 28 29 PM" src="https://github.com/SpiderStrategies/kalpa-tree/assets/3791116/269df937-ea01-42ea-9f77-25988a3cacfe">

**Comment by derekstory** [comment]
@scottoreilly I should confirm with you about the design before we make this change. The new design shows extra white-space/padding on the left/right of the selected node. When the selected node is a nested indented node, should the grey background be indented to match the indention of the nested nodes content or should it be all the way to the left (same as if it were a top node that has no indention)?

New design for reference:

<img width="1083" alt="296313671-59ef0fed-cf3a-4010-a79b-a94c03f9c643" src="https://github.com/SpiderStrategies/kalpa-tree/assets/3791116/7259ff44-466f-48d0-8cc2-5699a90a06cc">

**Comment by scottoreilly** [comment]
The actual selected state is indented, so it looks like this screenshot I took from the organisms section. It's not a valid state, but it does show what a non-root looks like.

<img width="1055" alt="2024-01-16_21-19-34" src="https://github.com/SpiderStrategies/kalpa-tree/assets/1259395/7a8d5c56-396b-4b01-8712-e353495d1609">

Here's another example higher up in the file.

<img width="1334" alt="2024-01-16_21-20-56" src="https://github.com/SpiderStrategies/kalpa-tree/assets/1259395/2384513a-8cef-4996-aa82-435206e093b4">

I'm really glad you reached out when you weren't sure, though, because there's a lot of garbage creeping into these designs. I had a long call with the designers today about cleaning things up, but it's going to take a while until that happens. They're mostly working on what looks good without a huge master plan, so if something seems off, it probably is.

**Comment by scottoreilly** [comment]
Crap, I just noticed a problem in just those two screenshots. The two trees are indented different amounts. I'd recommend going with the light gray indenting amounts because it's less, and I'll get that cleaned up.

**Comment by derekstory** [comment]
@scottoreilly Sounds good. Thanks for the clarification.

@nathanbowser I think we are good to proceed.

**Comment by derekstory** [comment]
@scottoreilly I'm wondering if that extra padding on the yellow highlight is compensating for a it not having an arrow there because it doesn't expand. But if it had a sibling that did expand and has an arrow, the left alignment of the highlighted backgrounds would jump when selecting different siblings. 

Also, not compensating for the missing arrow when highlighted could potentially look like its nested if it has a sibling before it with the extra content in front. 

I'm not sure if any of that made sense...  I can make some examples if it didn't.

**Comment by scottoreilly** [comment]
Yep, that makes sense and I’ll get them to fix the trees. Do you have enough information to code it in the meantime or is this blocking you?

**Comment by derekstory** [comment]
Yeah, I think we are good.

**Comment by nathanbowser** [comment]
@derekstory You should be able to `npm i kalpa-tree@latest` in your Impact branch. Ping me if you run into issues.
